all: befunge_interpreter befunge_interpreter2

befunge_interpreter: befunge_interpreter.c
	gcc -O3 -Wall befunge_interpreter.c -o befunge_interpreter

befunge_interpreter2: befunge_interpreter2.c
	gcc -O3 -Wall befunge_interpreter2.c -o befunge_interpreter2

clean:
	rm befunge_interpreter befunge_interpreter2
